name: Bump Script Version

on:
  push:
  pull_request:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      # Check if ReNXEnhanced.user.js has been modified since the last commit
      - name: Update Script Version
        id: version_code_check
        env:
          GIT_AUTH: ${{ secrets.GIT_AUTH }}
        run: |
          if ! git diff HEAD~1 --name-only | grep -q "ReNXEnhanced.user.js"; then
            echo "No changes to ReNXEnhanced.user.js since last commit"
            exit 0
          else
            echo "ReNXEnhanced.user.js file has been modified"
            # Get the previous SCRIPT_VERSION from the last commit
            PREVIOUS_SCRIPT_VERSION=$(git show HEAD~:ReNXEnhanced.user.js | sed -n '/@version/s/.*@version\s*//p' | xargs)

            # Get the current SCRIPT_VERSION from ReNXEnhanced.user.js
            SCRIPT_VERSION=$(sed -n '/@version/s/.*@version\s*//p' ReNXEnhanced.user.js | xargs)

            # Check if the SCRIPT_VERSION has been manually updated
            if [[ "$SCRIPT_VERSION" != "$PREVIOUS_SCRIPT_VERSION" ]]; then
              echo "SCRIPT_VERSION has been manually updated"
              echo "CREATE_RELEASE=false" >> $GITHUB_OUTPUT
              exit 0
            else
              echo 'SCRIPT_VERSION has NOT been manually updated'
              # Increment the SCRIPT_VERSION by 0.1
              NEW_SCRIPT_VERSION=$(awk -v prev="$SCRIPT_VERSION" 'BEGIN { printf "%.1f", prev+0.1 }')

              # Update the SCRIPT_VERSION in ReNXEnhanced.user.js, preserving spacing
              sed -i "/@version/ s/\(@version\s*\)[0-9.]\+/\1$NEW_SCRIPT_VERSION/" ReNXEnhanced.user.js
              if [[ $(git status) == *"nothing to commit, working tree clean"* ]]; then
                echo "Nothing to commit, working tree clean"
                exit 0
              fi
              git config user.name "GitHub Actions"
              git config user.email "actions@github.com"
              git remote set-url origin https://${{ secrets.GIT_AUTH }}@github.com/origamiofficial/ReNXEnhanced.git
              git add ReNXEnhanced.user.js
              git commit -m "Bump Script Version to $NEW_SCRIPT_VERSION"
              git push
              echo "New Version: $NEW_SCRIPT_VERSION"
              echo VERSION_CODE=$NEW_SCRIPT_VERSION >> $GITHUB_OUTPUT
              echo "CREATE_RELEASE=true" >> $GITHUB_OUTPUT
            fi
          fi
      - name: Create release
        if: steps.version_code_check.outputs.CREATE_RELEASE == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./ReNXEnhanced.user.js
          release_name: ${{ steps.version_code_check.outputs.VERSION_CODE }}
          tag: ${{ steps.version_code_check.outputs.VERSION_CODE }}
          make_latest: true
          overwrite: true